plugins {
    id 'java'
}

group = 'com.bx'
version = '1.0.0'

repositories {
    mavenCentral()

    maven {
        name = 'papermc'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }

    maven {
        name = 'jitpack'
        url = uri('https://jitpack.io')
    }

    maven {
        name = 'placeholderapi'
        url = uri('https://repo.extendedclip.com/releases/')
    }

    maven {
        name = 'essentialsx'
        url = uri('https://repo.essentialsx.net/releases/')
    }

    maven {
        name = 'codemc'
        url = uri('https://repo.codemc.io/repository/maven-public/')
    }
}

dependencies {
    // Main Bukkit/Paper API
    compileOnly 'io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT'

    // Don't allow these APIs to pull their own Bukkit/Paper versions.
    compileOnly('com.github.MilkBowl:VaultAPI:1.7') {
        transitive = false
    }

    compileOnly('me.clip:placeholderapi:2.11.6') {
        transitive = false
    }

    compileOnly('net.essentialsx:EssentialsX:2.21.2') {
        transitive = false
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filteringCharset = 'UTF-8'
}

jar {
    archiveBaseName = 'MagicSMP'
    archiveVersion = project.version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('build') {
    dependsOn tasks.named('jar')
}
