plugins {
    id 'java'
}

group = 'com.bx'
version = '1.0.0-updated'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://repo.codemc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2-R0.1-SNAPSHOT'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
    implementation 'org.mongodb:mongodb-driver-sync:5.5.1'
    implementation 'com.zaxxer:HikariCP:6.3.0'
    implementation 'redis.clients:jedis:6.2.0'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'com.mysql:mysql-connector-j:9.4.0'
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:none']
}

jar {
    archiveBaseName = 'MagicSMP'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}
